name: book_nook
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.1.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  font_awesome_flutter: ^10.5.0
  go_router: ^11.1.1
  google_fonts: ^6.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
  fonts:
    - family: GT_Sectra_Fine
      fonts:
        - asset: assets/fonts/GT_Sectra_Fine_Regular.ttf

    - family: Gilroy
      fonts:
        - asset: assets/fonts/Gilroy-Bold.ttf
